name: Go Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: 1.24

    - name: Install libpcap-dev
      run: sudo apt-get install -y libpcap-dev make

    - name: Get nmap dependencies
      run: make get_nmap_binary && make get_nmap_win_zip

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...
